### PR TITLE
[WIP] Account linking

### PR DESCRIPTION
**Pull request by RysingDragon**
This PR is to sync Minecraft and Discord accounts together. I believe I've got a good bit of it done, the main thing which stops me from going further is we need a way to store the Minecraft player to be gotten from the Discord side. 
We're going to need some kind of file storage which I'm not entirely sure on what the best way we should do so. I'd like input on how we should go about that.

### CODE REVIEW

**Comment by Mohron** [comment]
The bot operates on the Minecraft server so you shouldn't need to access any data from the Discord side as the MC side is guaranteed to be present.  That's why we can just store the user ID as a permissions option and call it a day.

**Comment by RysingDragon** [comment]
I'm not sure if you fully understand what I mean. I'm saying that given a Discord user, we need some kind of storage so we can get what the corresponding Minecraft user is.

**Comment by Mohron** [comment]
Nickname to match Username. But when would you need to know the MC account eq. on Discord if the user hasn't logged in?

**Comment by RysingDragon** [comment]
Nickname doesn't really seem like a great way to handle it as many users like to change their nicknames. One example I can think of off the top of my head is running commands in Minecraft from discord. We'd need to know their Minecraft user to know if they have sufficient permissions. I'm sure there'd be other cases too in the future once we get features rolling.

**Comment by Time6628** [comment]
Store the user's Discord ID, for example my Discord ID is 71371505652477952.

**Comment by RysingDragon** [comment]
That's what I was suggesting, I would store a Map of Discord user ID -> Minecraft player UUID. First we need some kind of file storage system set up which was what my initial comment was asking about how we should set one up.

**Comment by dualspiral** [comment]
If this works, go ahead and merge so we can get the ball rolling. We can make changes later before we start making this readily available.

**Comment by dualspiral** [comment]
\o/

**Pull request merged**
