### PR TITLE
create discord bot

### PR DESCRIPTION
**Pull request by RysingDragon**
I know it's a very small PR but I think this is necessary to help us start get rolling again. There's only one thing I have to comment on right now regarding the bot. As you probably know from discord bots you can set the avatar. 
How should we do this? We can either have the server owner specify an image url in the config or place an image file somewhere in the server directory and we use that. I'm more leaning towards using a url.

### CODE REVIEW

**Comment by Time6628** [comment]
Discord bot profile pictures are set through the discord bots page. I do not think you can set the profile picture through JDA.

**Comment by RysingDragon** [comment]
It actually is possibly to change profile pictures through the api. 
<code>
DiscordBot.getInstance().getJda().getSelfUser().getManager().setAvatar(Icon.from(File avatar));
</code>
That would be how to do it with a file. Icon.from() also has an overloaded method to take an InputStream so we can use a url.
I know we can do it through the discord page but this way might be a bit easier on owners for changing bot settings as it'd be all in one place.

**Comment by RysingDragon** [comment]
Alright I'm happy with this right now, anything needing to be changed before merge?

**Comment by dualspiral** [comment]
Looks reasonable to me, but my knowledge of JDA and Discrod bridges is shaky - so if one of the others could just confirm the logic is sound, we can merge and get things rolling again.

**Comment by Mohron** [comment]
If it's working, looks good to me. Did you run a test case at all?

**Comment by RysingDragon** [comment]
yep, I tested it with an inject into the AboutCommand class and giving the name of the bot.

**Pull request merged**
